### PR TITLE
Math magicians: events

### PR DESCRIPTION
**Pull request by fabgrel10**
In this PR:

- [x] Create the logic directory.
- [x] Add calculate.js and operate.js into a logic directory.
- [x] Implement the logic to use  calculate.js and operate.js.

### CODE REVIEW

**Review by rukundoeric — CHANGES_REQUESTED** [review]
Hi @fabgrel10, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 

## Required Changes ♻️
  - [ ] There are too many useless files under `Calculator` directory. Kindly remove them.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - [ ] Check the comments under the review.

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by fabgrel10** [comment]
Thank you for the review @rukundoeric , could you tell me which useless files you referred to? All of the files/components in that directory are accomplishing a specific function. Did you reviewed the feat/events branch?

**Comment by rukundoeric** [comment]
> Thank you for the review @rukundoeric , could you tell me which useless files you referred to? All of the files/components in that directory are accomplishing a specific function. Did you reviewed the feat/events branch?

Hello @fabgrel10, this is what I was talking about.

scrnli_1_5_2022_5-18-02 AM

**Comment by fabgrel10** [comment]
I didn't notice those files until now, those were autogenerated by vscode somehow. I'm removing them now and requesting another review. Thank you again @rukundoeric!

**Review by rukundoeric — APPROVED** [review]
Hi @fabgrel10,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_


Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------
>As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
